spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      #value-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
      schema.registry.url: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile:
        - microk8s

  kafka:
    bootstrap-servers: kafka-broker.kafka:9092
    properties:
      schema.registry.url: http://kafka-schema.kafka:8081