spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      #value-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
      schema.registry.url: http://localhost:8081