apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

configMapGenerator:
  - name: simple-consumer-grp1-application-yml
    behavior: create
    files:
      - simple-consumer-grp1/application-microk8s.yml

  - name: simple-consumer-grp2-application-yml
    behavior: create
    files:
      - simple-consumer-grp2/application-microk8s.yml

  - name: simple-producer-application-yml
    behavior: create
    files:
      - simple-producer/application-microk8s.yml

replicas:
  - name: simple-producer
    count: 1
  - name: simple-consumer-grp1
    count: 5
  - name: simple-consumer-grp2
    count: 5

patchesStrategicMerge:
  - simple-producer/simple-producer.yml
  - simple-consumer-grp1/simple-consumer-grp1.yml
  - simple-consumer-grp2/simple-consumer-grp2.yml
